Models/Database/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Projekat.Models.View;

namespace Projekat.Models.Database
{
    public class User : IdentityUser
    {

        [Required]
        public string firstName { get; set; }
        [Required]
        public string lastName { get; set; }
        [Required]
        public string gender { get; set; }

        public bool isActive { get; set; }

        public bool isDeleted { get; set; }

        public int tokenCount { get; set; }

        public ICollection<Auction> auctions { get; set; }

        public ICollection<Order> orders { get; set; }

        public ICollection<Bid> Bids { get; set; }





    }

    public class UserProfile : Profile {
        public UserProfile(){
            base.CreateMap<RegisterModel, User>()
            .ForMember (
                destination => destination.Email,
                options => options.MapFrom( data => data.email)
            )
             .ForMember (
                destination => destination.UserName,
                options => options.MapFrom( data => data.username)
            ).ReverseMap();
        }
    }

    // public class UserConfiguration : IEntityTypeConfiguration<User>{ 
    //     public void Configure(EntityTypeBuilder<User> builder){ 
    //         builder.Property( user => user.id).ValueGeneratedOnAdd();
    //         builder.HasData( new User () { 
    //             id = 1, firstName = "Milan",
    //              lastName = "Boskovic", email = "jovbosko1@gmail.com", 
    //              password= "1", gender = "male", username = "Xtender"});
    //     }
    // }
}

Controllers/PaymentController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Projekat.Models.Database;
using Projekat.Models.View;

namespace Projekat.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private AuctionContext context;
        private UserManager<User> userManager;
        private SignInManager<User> signInManager;

        public PaymentController(AuctionContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult BuyTokens()
        {
            return View("BuyTokens");
        }

        public async Task<string> addPayment(string amount)
        {

            Order order = new Order();
            order.orderDate = DateTime.Now;
            order.amount = int.Parse(amount);
            order.price = int.Parse(amount);
            order.userId = this.userManager.GetUserId(User);
            this.context.order.Add(order);


            User loggedInUser = this.context.Users.Find(this.userManager.GetUserId(User));
            loggedInUser.tokenCount += int.Parse(amount);
            this.context.Users.Update(loggedInUser);
            this.context.SaveChanges();

            await signInManager.RefreshSignInAsync(loggedInUser);


            return "Succesfully created order!";
        }


        public IActionResult Payments(string page){ 

            int pageNumber = int.Parse(page);
            pageNumber++;
            int pageSize = 10;
            
            PaymentsModel model = new PaymentsModel();
            User loggedInUser = this.context.Users.Find(this.userManager.GetUserId(User));
            model.Orders = this.context.order.Where(order => order.userId == loggedInUser.Id).Skip((pageNumber-1)*pageSize).Take(pageSize).ToList();
            model.pageNumber = pageNumber;
            return View(model);
        }

    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Projekat.Models.Database;
using Projekat.Models.View;

namespace Projekat.Controllers
{

    public class UserController : Controller
    {
        private AuctionContext context;

        private UserManager<User> userManager;

        private SignInManager<User> signInManager;

        private IMapper mapper;

        public UserController(AuctionContext context, UserManager<User> userManager, IMapper mapper, SignInManager<User> signInManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.mapper = mapper;
            this.signInManager = signInManager;
        }


        public IActionResult isEmailUnique(string email)
        {
            bool exist = this.context.Users.Where(user => user.Email == email).Any();

            if (exist)
            {
                return Json("Email already taken");
            }
            else
            {
                return Json(true);
            }

        }

        public bool isEmailUniqueBool(string email)
        {
            bool exist = this.context.Users.Where(user => user.Email == email).Any();

            if (exist)
            {
                return false;
            }
            else
            {
                return true;
            }

        }

        public IActionResult isUserNameUnique(string username)
        {
            bool exist = this.context.Users.Where(user => user.UserName == username).Any();

            if (exist)
            {
                return Json("Username already taken");
            }
            else
            {
                return Json(true);
            }

        }

        public bool isUserNameUniqueBool(string username)
        {
            bool exist = this.context.Users.Where(user => user.UserName == username).Any();

            if (exist)
            {
                return false;
            }
            else
            {
                return true;
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = this.mapper.Map<User>(model);
            user.tokenCount = 0;

            IdentityResult result = await this.userManager.CreateAsync(user, model.password);

            if (!result.Succeeded)
            {
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }

            result = await this.userManager.AddToRoleAsync(user, Roles.user.Name);

            if (!result.Succeeded)
            {
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }

            return RedirectToAction(nameof(SearchController.Index), "Search");



        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateModel model)
        {

            User loggedInUser = await this.userManager.GetUserAsync(base.User);

            if (loggedInUser.UserName != model.username)
            {
                if (!isUserNameUniqueBool(model.username))
                {
                    ModelState.AddModelError("", "User already taken!!!");
                    return View(model);
                }
            }

            if (loggedInUser.Email != model.email)
            {
                if (!isEmailUniqueBool(model.email))
                {
                    ModelState.AddModelError("", "Email already taken!!!");
                    return View(model);
                }
            }

            loggedInUser.PasswordHash = this.userManager.PasswordHasher.HashPassword(loggedInUser, model.password);

            loggedInUser.UserName = model.username;
            loggedInUser.NormalizedUserName = model.username.ToUpper();
            loggedInUser.firstName = model.firstName;
            loggedInUser.lastName = model.lastName;
            loggedInUser.Email = model.email;
            loggedInUser.NormalizedEmail = model.email.ToUpper();
            loggedInUser.gender = model.gender;


            await this.userManager.UpdateAsync(loggedInUser);

            this.context.SaveChanges();

            return RedirectToAction(nameof(SearchController.Index), "Search");


        }


        public async Task<IActionResult> Register(string isUpdate)
        {




            if (isUpdate == "update")
            {
                UpdateModel model = new UpdateModel();
                User loggedInUser = await this.userManager.GetUserAsync(base.User);
                User userDB = this.context.Users.Where(u => u.UserName == loggedInUser.UserName).FirstOrDefault();
                model.username = userDB.UserName;
                model.firstName = userDB.firstName;
                model.lastName = userDB.lastName;
                model.gender = userDB.gender;
                model.email = userDB.Email;
                model.password = userDB.PasswordHash;
                model.confirmPassword = userDB.PasswordHash;
                model.isUpdate = true;
                return View("Update", model);


            }
            else
            {
                RegisterModel model = new RegisterModel();
                model.isUpdate = false;
                return View(model);

            }

        }


        public IActionResult Login(string returnUrl)
        {
            LoginModel model = new LoginModel() { returnUrl = returnUrl };
            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            User user = await this.context.Users.Where(u => u.UserName == model.username).FirstOrDefaultAsync();
            if(user == null){
                ModelState.AddModelError("", "Invalid username or password");
                return View(model);
            }
            if (user.isDeleted)
            {
                ModelState.AddModelError("", "Your account is deleted!");
                return View(model);

            }
            var result = await this.signInManager.PasswordSignInAsync(model.username, model.password, false, false);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Invalid username or password");
                return View(model);
            }



            if (model.returnUrl != null)
                return Redirect(model.returnUrl);
            else
            {
                return RedirectToAction(nameof(SearchController.Index), "Search");
            }
        }


        public async Task<IActionResult> Logout()
        {

            await this.signInManager.SignOutAsync();
            return RedirectToAction(nameof(SearchController.Index), "Search");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> getUsersToApprove()
        {
            string signedInUser = this.userManager.GetUserId(User);
            List<User> users = await this.context.Users.Where(u => u.Id != signedInUser).ToListAsync();
            AdminApproveModel model = new AdminApproveModel();
            model.Users = users;
            return View("AdminApprove", model);

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> getAuctionsToApprove()
        {
            List<Auction> auctions = await this.context.auction.Where(u => u.state == State.DRAFT).ToListAsync();
            List<string> images = new List<string>();
            foreach (Auction auction in auctions)
            {
                string image = Convert.ToBase64String(auction.image);
                images.Add(image);
            }
            AdminApproveModel model = new AdminApproveModel();
            model.Auctions = auctions;
            model.images = images;
            return View("AdminApproveAuctions", model);

        }



        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> deleteUser(string id)
        {
            User user = await this.context.Users.Where(u => u.Id == id).SingleAsync();
            user.isDeleted = true;
            this.context.Users.Update(user);

            List<Auction> auctions = this.context.auction.Where(a => a.userId == id && (a.state == State.READY || a.state == State.OPEN)).ToList();

            foreach (Auction auction in auctions)
            {
                auction.state = State.EXPIRED;
                this.context.auction.Update(auction);
            }
            await this.context.SaveChangesAsync();

            return await getUsersToApprove();
        }



    }



}

Views/Shared/SignalR.cshtml
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/signalr/dist/browser/signalr.min.js"></script>
<script src="~/js/auction.js"></script>

Views/Shared/User.cshtml
@using Microsoft.AspNetCore.Identity
@using Projekat.Models.Database
@using System.Security.Claims
@inject SignInManager<User> signInManager

@{ 
    string fullName = "";
    string role = "";
    string tokens = "";
    foreach(Claim claim in User.Claims){
        if(claim.Type.Equals("fullName")){
            fullName = claim.Value;
        }
        if(claim.Type.Equals("tokens")){
            tokens = claim.Value;
        }
        if(claim.Type.Equals(ClaimTypes.Role)){
            role = claim.Value;
        }
    }
    
}

<ul class="navbar-nav">
    @if(signInManager.IsSignedIn( User)){

        if(role == "Admin"){
            <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="getUsersToApprove">Users</a></li>
            <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="getAuctionsToApprove">Approve Auctions</a></li>


        }

        @* <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="Register">Welcome @fullName</a></li> *@
        <li class="nav-item"><a  id="tokeni" class="nav-link" >@tokens</a></li>
        <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="Logout">Log Out</a></li>
        <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="Register" asp-route-isUpdate="update">Account</a></li>



    }
    else{
        <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="Register" asp-route-isUpdate="not">Register</a></li>
        <li class="nav-item"><a  class="nav-link" asp-controller="User" asp-action="Login">Login</a></li>

    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auction</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container pl-0 pr-0">
                <a class="navbar-brand" asp-area="" asp-controller="Search" asp-action="Index">Auction</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="User"></partial>
                    <ul class="navbar-nav flex-grow-1">
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="CreateAuction">Create Auction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="MyAuctions">My Auctions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="BuyTokens">Buy Tokens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Payments" asp-route-page="0">My Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="WonAuctions">Won Auctions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Projekat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>